/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Variant;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AnimatedGifAllOf
 */
public class AnimatedGifAllOfTest {
    private final AnimatedGifAllOf model = new AnimatedGifAllOf();

    /**
     * Model tests for AnimatedGifAllOf
     */
    @Test
    public void testAnimatedGifAllOf() {
        // TODO: test AnimatedGifAllOf
    }

    /**
     * Test the property 'previewImageUrl'
     */
    @Test
    public void previewImageUrlTest() {
        // TODO: test previewImageUrl
    }

    /**
     * Test the property 'variants'
     */
    @Test
    public void variantsTest() {
        // TODO: test variants
    }

}
