/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AnimatedGif;
import com.konfigthis.client.model.Media;
import com.konfigthis.client.model.Photo;
import com.konfigthis.client.model.Variant;
import com.konfigthis.client.model.Video;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AnimatedGif
 */
public class AnimatedGifTest {
    private final AnimatedGif model = new AnimatedGif();

    /**
     * Model tests for AnimatedGif
     */
    @Test
    public void testAnimatedGif() {
        // TODO: test AnimatedGif
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'mediaKey'
     */
    @Test
    public void mediaKeyTest() {
        // TODO: test mediaKey
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'previewImageUrl'
     */
    @Test
    public void previewImageUrlTest() {
        // TODO: test previewImageUrl
    }

    /**
     * Test the property 'variants'
     */
    @Test
    public void variantsTest() {
        // TODO: test variants
    }

}
