/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ClientDisconnectedProblem;
import com.konfigthis.client.model.ClientForbiddenProblem;
import com.konfigthis.client.model.ConflictProblem;
import com.konfigthis.client.model.ConnectionExceptionProblem;
import com.konfigthis.client.model.DisallowedResourceProblem;
import com.konfigthis.client.model.DuplicateRuleProblem;
import com.konfigthis.client.model.FieldUnauthorizedProblem;
import com.konfigthis.client.model.GenericProblem;
import com.konfigthis.client.model.InvalidRequestProblem;
import com.konfigthis.client.model.InvalidRuleProblem;
import com.konfigthis.client.model.NonCompliantRulesProblem;
import com.konfigthis.client.model.Oauth1PermissionsProblem;
import com.konfigthis.client.model.OperationalDisconnectProblem;
import com.konfigthis.client.model.Problem;
import com.konfigthis.client.model.ResourceNotFoundProblem;
import com.konfigthis.client.model.ResourceUnauthorizedProblem;
import com.konfigthis.client.model.ResourceUnavailableProblem;
import com.konfigthis.client.model.RulesCapProblem;
import com.konfigthis.client.model.UnsupportedAuthenticationProblem;
import com.konfigthis.client.model.UsageCapExceededProblem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConnectionExceptionProblem
 */
public class ConnectionExceptionProblemTest {
    private final ConnectionExceptionProblem model = new ConnectionExceptionProblem();

    /**
     * Model tests for ConnectionExceptionProblem
     */
    @Test
    public void testConnectionExceptionProblem() {
        // TODO: test ConnectionExceptionProblem
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'connectionIssue'
     */
    @Test
    public void connectionIssueTest() {
        // TODO: test connectionIssue
    }

}
