/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Media;
import com.konfigthis.client.model.Place;
import com.konfigthis.client.model.Poll;
import com.konfigthis.client.model.Topic;
import com.konfigthis.client.model.Tweet;
import com.konfigthis.client.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Expansions
 */
public class ExpansionsTest {
    private final Expansions model = new Expansions();

    /**
     * Model tests for Expansions
     */
    @Test
    public void testExpansions() {
        // TODO: test Expansions
    }

    /**
     * Test the property 'media'
     */
    @Test
    public void mediaTest() {
        // TODO: test media
    }

    /**
     * Test the property 'places'
     */
    @Test
    public void placesTest() {
        // TODO: test places
    }

    /**
     * Test the property 'polls'
     */
    @Test
    public void pollsTest() {
        // TODO: test polls
    }

    /**
     * Test the property 'topics'
     */
    @Test
    public void topicsTest() {
        // TODO: test topics
    }

    /**
     * Test the property 'tweets'
     */
    @Test
    public void tweetsTest() {
        // TODO: test tweets
    }

    /**
     * Test the property 'users'
     */
    @Test
    public void usersTest() {
        // TODO: test users
    }

}
