/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CashtagEntity;
import com.konfigthis.client.model.FullTextEntitiesAnnotationsInner;
import com.konfigthis.client.model.HashtagEntity;
import com.konfigthis.client.model.MentionEntity;
import com.konfigthis.client.model.UrlEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FullTextEntities
 */
public class FullTextEntitiesTest {
    private final FullTextEntities model = new FullTextEntities();

    /**
     * Model tests for FullTextEntities
     */
    @Test
    public void testFullTextEntities() {
        // TODO: test FullTextEntities
    }

    /**
     * Test the property 'annotations'
     */
    @Test
    public void annotationsTest() {
        // TODO: test annotations
    }

    /**
     * Test the property 'cashtags'
     */
    @Test
    public void cashtagsTest() {
        // TODO: test cashtags
    }

    /**
     * Test the property 'hashtags'
     */
    @Test
    public void hashtagsTest() {
        // TODO: test hashtags
    }

    /**
     * Test the property 'mentions'
     */
    @Test
    public void mentionsTest() {
        // TODO: test mentions
    }

    /**
     * Test the property 'urls'
     */
    @Test
    public void urlsTest() {
        // TODO: test urls
    }

}
