/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Expansions;
import com.konfigthis.client.model.Get2TweetsSearchAllResponseMeta;
import com.konfigthis.client.model.Problem;
import com.konfigthis.client.model.Tweet;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Get2TweetsSearchRecentResponse
 */
public class Get2TweetsSearchRecentResponseTest {
    private final Get2TweetsSearchRecentResponse model = new Get2TweetsSearchRecentResponse();

    /**
     * Model tests for Get2TweetsSearchRecentResponse
     */
    @Test
    public void testGet2TweetsSearchRecentResponse() {
        // TODO: test Get2TweetsSearchRecentResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'includes'
     */
    @Test
    public void includesTest() {
        // TODO: test includes
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

}
