/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MuteUserMutationResponseData
 */
public class MuteUserMutationResponseDataTest {
    private final MuteUserMutationResponseData model = new MuteUserMutationResponseData();

    /**
     * Model tests for MuteUserMutationResponseData
     */
    @Test
    public void testMuteUserMutationResponseData() {
        // TODO: test MuteUserMutationResponseData
    }

    /**
     * Test the property 'muting'
     */
    @Test
    public void mutingTest() {
        // TODO: test muting
    }

}
