/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PollOption;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Poll
 */
public class PollTest {
    private final Poll model = new Poll();

    /**
     * Model tests for Poll
     */
    @Test
    public void testPoll() {
        // TODO: test Poll
    }

    /**
     * Test the property 'durationMinutes'
     */
    @Test
    public void durationMinutesTest() {
        // TODO: test durationMinutes
    }

    /**
     * Test the property 'endDatetime'
     */
    @Test
    public void endDatetimeTest() {
        // TODO: test endDatetime
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'votingStatus'
     */
    @Test
    public void votingStatusTest() {
        // TODO: test votingStatus
    }

}
