/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetWithheld
 */
public class TweetWithheldTest {
    private final TweetWithheld model = new TweetWithheld();

    /**
     * Model tests for TweetWithheld
     */
    @Test
    public void testTweetWithheld() {
        // TODO: test TweetWithheld
    }

    /**
     * Test the property 'copyright'
     */
    @Test
    public void copyrightTest() {
        // TODO: test copyright
    }

    /**
     * Test the property 'countryCodes'
     */
    @Test
    public void countryCodesTest() {
        // TODO: test countryCodes
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

}
