/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TweetComplianceSchemaTweet;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetTakedownComplianceSchema
 */
public class TweetTakedownComplianceSchemaTest {
    private final TweetTakedownComplianceSchema model = new TweetTakedownComplianceSchema();

    /**
     * Model tests for TweetTakedownComplianceSchema
     */
    @Test
    public void testTweetTakedownComplianceSchema() {
        // TODO: test TweetTakedownComplianceSchema
    }

    /**
     * Test the property 'eventAt'
     */
    @Test
    public void eventAtTest() {
        // TODO: test eventAt
    }

    /**
     * Test the property 'quoteTweetId'
     */
    @Test
    public void quoteTweetIdTest() {
        // TODO: test quoteTweetId
    }

    /**
     * Test the property 'tweet'
     */
    @Test
    public void tweetTest() {
        // TODO: test tweet
    }

    /**
     * Test the property 'withheldInCountries'
     */
    @Test
    public void withheldInCountriesTest() {
        // TODO: test withheldInCountries
    }

}
