/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DmEventReferencedTweetsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetEditComplianceObjectSchema
 */
public class TweetEditComplianceObjectSchemaTest {
    private final TweetEditComplianceObjectSchema model = new TweetEditComplianceObjectSchema();

    /**
     * Model tests for TweetEditComplianceObjectSchema
     */
    @Test
    public void testTweetEditComplianceObjectSchema() {
        // TODO: test TweetEditComplianceObjectSchema
    }

    /**
     * Test the property 'editTweetIds'
     */
    @Test
    public void editTweetIdsTest() {
        // TODO: test editTweetIds
    }

    /**
     * Test the property 'eventAt'
     */
    @Test
    public void eventAtTest() {
        // TODO: test eventAt
    }

    /**
     * Test the property 'initialTweetId'
     */
    @Test
    public void initialTweetIdTest() {
        // TODO: test initialTweetId
    }

    /**
     * Test the property 'tweet'
     */
    @Test
    public void tweetTest() {
        // TODO: test tweet
    }

}
