/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContextAnnotation;
import com.konfigthis.client.model.FullTextEntities;
import com.konfigthis.client.model.ReplySettings;
import com.konfigthis.client.model.TweetAttachments;
import com.konfigthis.client.model.TweetEditControls;
import com.konfigthis.client.model.TweetGeo;
import com.konfigthis.client.model.TweetNonPublicMetrics;
import com.konfigthis.client.model.TweetOrganicMetrics;
import com.konfigthis.client.model.TweetPromotedMetrics;
import com.konfigthis.client.model.TweetPublicMetrics;
import com.konfigthis.client.model.TweetReferencedTweetsInner;
import com.konfigthis.client.model.TweetWithheld;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Tweet
 */
public class TweetTest {
    private final Tweet model = new Tweet();

    /**
     * Model tests for Tweet
     */
    @Test
    public void testTweet() {
        // TODO: test Tweet
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'authorId'
     */
    @Test
    public void authorIdTest() {
        // TODO: test authorId
    }

    /**
     * Test the property 'contextAnnotations'
     */
    @Test
    public void contextAnnotationsTest() {
        // TODO: test contextAnnotations
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    public void conversationIdTest() {
        // TODO: test conversationId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'editControls'
     */
    @Test
    public void editControlsTest() {
        // TODO: test editControls
    }

    /**
     * Test the property 'editHistoryTweetIds'
     */
    @Test
    public void editHistoryTweetIdsTest() {
        // TODO: test editHistoryTweetIds
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'geo'
     */
    @Test
    public void geoTest() {
        // TODO: test geo
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'inReplyToUserId'
     */
    @Test
    public void inReplyToUserIdTest() {
        // TODO: test inReplyToUserId
    }

    /**
     * Test the property 'lang'
     */
    @Test
    public void langTest() {
        // TODO: test lang
    }

    /**
     * Test the property 'nonPublicMetrics'
     */
    @Test
    public void nonPublicMetricsTest() {
        // TODO: test nonPublicMetrics
    }

    /**
     * Test the property 'organicMetrics'
     */
    @Test
    public void organicMetricsTest() {
        // TODO: test organicMetrics
    }

    /**
     * Test the property 'possiblySensitive'
     */
    @Test
    public void possiblySensitiveTest() {
        // TODO: test possiblySensitive
    }

    /**
     * Test the property 'promotedMetrics'
     */
    @Test
    public void promotedMetricsTest() {
        // TODO: test promotedMetrics
    }

    /**
     * Test the property 'publicMetrics'
     */
    @Test
    public void publicMetricsTest() {
        // TODO: test publicMetrics
    }

    /**
     * Test the property 'referencedTweets'
     */
    @Test
    public void referencedTweetsTest() {
        // TODO: test referencedTweets
    }

    /**
     * Test the property 'replySettings'
     */
    @Test
    public void replySettingsTest() {
        // TODO: test replySettings
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'withheld'
     */
    @Test
    public void withheldTest() {
        // TODO: test withheld
    }

}
