/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserComplianceSchemaUser;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserScrubGeoObjectSchema
 */
public class UserScrubGeoObjectSchemaTest {
    private final UserScrubGeoObjectSchema model = new UserScrubGeoObjectSchema();

    /**
     * Model tests for UserScrubGeoObjectSchema
     */
    @Test
    public void testUserScrubGeoObjectSchema() {
        // TODO: test UserScrubGeoObjectSchema
    }

    /**
     * Test the property 'eventAt'
     */
    @Test
    public void eventAtTest() {
        // TODO: test eventAt
    }

    /**
     * Test the property 'upToTweetId'
     */
    @Test
    public void upToTweetIdTest() {
        // TODO: test upToTweetId
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
