/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserProfileModificationObjectSchema;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserProfileModificationComplianceSchema
 */
public class UserProfileModificationComplianceSchemaTest {
    private final UserProfileModificationComplianceSchema model = new UserProfileModificationComplianceSchema();

    /**
     * Model tests for UserProfileModificationComplianceSchema
     */
    @Test
    public void testUserProfileModificationComplianceSchema() {
        // TODO: test UserProfileModificationComplianceSchema
    }

    /**
     * Test the property 'userProfileModification'
     */
    @Test
    public void userProfileModificationTest() {
        // TODO: test userProfileModification
    }

}
