/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Variant;
import com.konfigthis.client.model.VideoAllOfNonPublicMetrics;
import com.konfigthis.client.model.VideoAllOfOrganicMetrics;
import com.konfigthis.client.model.VideoAllOfPromotedMetrics;
import com.konfigthis.client.model.VideoAllOfPublicMetrics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VideoAllOf
 */
public class VideoAllOfTest {
    private final VideoAllOf model = new VideoAllOf();

    /**
     * Model tests for VideoAllOf
     */
    @Test
    public void testVideoAllOf() {
        // TODO: test VideoAllOf
    }

    /**
     * Test the property 'durationMs'
     */
    @Test
    public void durationMsTest() {
        // TODO: test durationMs
    }

    /**
     * Test the property 'nonPublicMetrics'
     */
    @Test
    public void nonPublicMetricsTest() {
        // TODO: test nonPublicMetrics
    }

    /**
     * Test the property 'organicMetrics'
     */
    @Test
    public void organicMetricsTest() {
        // TODO: test organicMetrics
    }

    /**
     * Test the property 'previewImageUrl'
     */
    @Test
    public void previewImageUrlTest() {
        // TODO: test previewImageUrl
    }

    /**
     * Test the property 'promotedMetrics'
     */
    @Test
    public void promotedMetricsTest() {
        // TODO: test promotedMetrics
    }

    /**
     * Test the property 'publicMetrics'
     */
    @Test
    public void publicMetricsTest() {
        // TODO: test publicMetrics
    }

    /**
     * Test the property 'variants'
     */
    @Test
    public void variantsTest() {
        // TODO: test variants
    }

}
