/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.62
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id, Poll, and Card URI.
 */
@ApiModel(description = "Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id, Poll, and Card URI.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TweetCreateRequestMedia {
  public static final String SERIALIZED_NAME_MEDIA_IDS = "media_ids";
  @SerializedName(SERIALIZED_NAME_MEDIA_IDS)
  private List<String> mediaIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_TAGGED_USER_IDS = "tagged_user_ids";
  @SerializedName(SERIALIZED_NAME_TAGGED_USER_IDS)
  private List<String> taggedUserIds = null;

  public TweetCreateRequestMedia() {
  }

  public TweetCreateRequestMedia mediaIds(List<String> mediaIds) {
    
    
    
    
    this.mediaIds = mediaIds;
    return this;
  }

  public TweetCreateRequestMedia addMediaIdsItem(String mediaIdsItem) {
    this.mediaIds.add(mediaIdsItem);
    return this;
  }

   /**
   * A list of Media Ids to be attached to a created Tweet.
   * @return mediaIds
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A list of Media Ids to be attached to a created Tweet.")

  public List<String> getMediaIds() {
    return mediaIds;
  }


  public void setMediaIds(List<String> mediaIds) {
    
    
    
    this.mediaIds = mediaIds;
  }


  public TweetCreateRequestMedia taggedUserIds(List<String> taggedUserIds) {
    
    
    
    
    this.taggedUserIds = taggedUserIds;
    return this;
  }

  public TweetCreateRequestMedia addTaggedUserIdsItem(String taggedUserIdsItem) {
    if (this.taggedUserIds == null) {
      this.taggedUserIds = new ArrayList<>();
    }
    this.taggedUserIds.add(taggedUserIdsItem);
    return this;
  }

   /**
   * A list of User Ids to be tagged in the media for created Tweet.
   * @return taggedUserIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of User Ids to be tagged in the media for created Tweet.")

  public List<String> getTaggedUserIds() {
    return taggedUserIds;
  }


  public void setTaggedUserIds(List<String> taggedUserIds) {
    
    
    
    this.taggedUserIds = taggedUserIds;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TweetCreateRequestMedia instance itself
   */
  public TweetCreateRequestMedia putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetCreateRequestMedia tweetCreateRequestMedia = (TweetCreateRequestMedia) o;
    return Objects.equals(this.mediaIds, tweetCreateRequestMedia.mediaIds) &&
        Objects.equals(this.taggedUserIds, tweetCreateRequestMedia.taggedUserIds)&&
        Objects.equals(this.additionalProperties, tweetCreateRequestMedia.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mediaIds, taggedUserIds, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetCreateRequestMedia {\n");
    sb.append("    mediaIds: ").append(toIndentedString(mediaIds)).append("\n");
    sb.append("    taggedUserIds: ").append(toIndentedString(taggedUserIds)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("media_ids");
    openapiFields.add("tagged_user_ids");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("media_ids");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TweetCreateRequestMedia
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TweetCreateRequestMedia.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TweetCreateRequestMedia is not found in the empty JSON string", TweetCreateRequestMedia.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TweetCreateRequestMedia.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the required json array is present
      if (jsonObj.get("media_ids") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("media_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `media_ids` to be an array in the JSON string but got `%s`", jsonObj.get("media_ids").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tagged_user_ids") != null && !jsonObj.get("tagged_user_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tagged_user_ids` to be an array in the JSON string but got `%s`", jsonObj.get("tagged_user_ids").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TweetCreateRequestMedia.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TweetCreateRequestMedia' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TweetCreateRequestMedia> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TweetCreateRequestMedia.class));

       return (TypeAdapter<T>) new TypeAdapter<TweetCreateRequestMedia>() {
           @Override
           public void write(JsonWriter out, TweetCreateRequestMedia value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TweetCreateRequestMedia read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TweetCreateRequestMedia instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TweetCreateRequestMedia given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TweetCreateRequestMedia
  * @throws IOException if the JSON string is invalid with respect to TweetCreateRequestMedia
  */
  public static TweetCreateRequestMedia fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TweetCreateRequestMedia.class);
  }

 /**
  * Convert an instance of TweetCreateRequestMedia to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

