openapi: 3.0.0
info:
  contact:
    name: Twitter Developers
    url: https://developer.twitter.com/
    x-twitter: twitter
  description: Twitter API v2 available endpoints
  license:
    name: Twitter Developer Agreement and Policy
    url: https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
  termsOfService: https://developer.twitter.com/en/developer-terms/agreement-and-policy.html
  title: Twitter API v2
  version: "2.62"
  x-apisguru-categories:
  - social
  x-logo:
    url: https://twitter.com/twitter/profile_image?size=original
  x-origin:
  - version: "3.0"
    format: openapi
    url: https://api.twitter.com/2/openapi.json
  x-providerName: twitter.com
  x-serviceName: current
  x-tags:
  - pii
  x-konfig-ignore:
    object-with-no-properties: true
    potential-incorrect-type: true
servers:
- description: Twitter API
  url: https://api.twitter.com
tags:
- description: "Endpoints related to retrieving, searching, and modifying Tweets"
  name: Tweets
- description: "Endpoints related to retrieving, managing relationships of Users"
  name: Users
- description: "Endpoints related to retrieving, managing Lists"
  name: Lists
- description: Endpoints related to keeping Twitter data in your systems compliant
  name: Compliance
- description: "Endpoints related to retrieving, managing Direct Messages"
  name: Direct Messages
- description: "Endpoints related to retrieving, managing Spaces"
  name: Spaces
- description: "Endpoints related to retrieving, managing bookmarks of a user"
  name: Bookmarks
- description: Miscellaneous endpoints for general API functionality
  name: General
paths:
  /2/compliance/jobs:
    get:
      description: Returns recent Compliance Jobs for a given job type and optional
        job status
      operationId: Compliance_listJobs
      security:
      - BearerToken: []
      summary: List Compliance Jobs
      tags:
      - Compliance
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-compliance-jobs
      x-accepts: application/json
    post:
      description: Creates a compliance for the given job type
      operationId: Compliance_createJob
      security:
      - BearerToken: []
      summary: Create compliance job
      tags:
      - Compliance
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-compliance-jobs
      x-content-type: application/json
      x-accepts: application/json
  /2/compliance/jobs/{id}:
    get:
      description: Returns a single Compliance Job by ID
      operationId: Compliance_getJobById
      security:
      - BearerToken: []
      summary: Get Compliance Job
      tags:
      - Compliance
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-compliance-jobs-id
      x-accepts: application/json
  /2/dm_conversations:
    post:
      description: Creates a new DM Conversation.
      operationId: DirectMessages_createNewDmConversation
      security:
      - OAuth2UserToken:
        - dm.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Create a new DM Conversation
      tags:
      - Direct Messages
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-dm_conversations
      x-content-type: application/json
      x-accepts: application/json
  /2/dm_conversations/with/{participant_id}/dm_events:
    get:
      description: Returns DM Events for a DM Conversation
      operationId: DirectMessages_getDmEvents
      security:
      - OAuth2UserToken:
        - dm.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get DM Events for a DM Conversation
      tags:
      - Direct Messages
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-dm_conversations-with-participant_id-dm_events
      x-accepts: application/json
  /2/dm_conversations/with/{participant_id}/messages:
    post:
      description: Creates a new message for a DM Conversation with a participant
        user by ID
      operationId: DirectMessages_sendNewMessageToUser
      security:
      - OAuth2UserToken:
        - dm.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Send a new message to a user
      tags:
      - Direct Messages
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-dm_conversations-with-participant_id-messages
      x-content-type: application/json
      x-accepts: application/json
  /2/dm_conversations/{dm_conversation_id}/messages:
    post:
      description: Creates a new message for a DM Conversation specified by DM Conversation
        ID
      operationId: DirectMessages_sendNewMessageToDmConversation
      security:
      - OAuth2UserToken:
        - dm.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Send a new message to a DM Conversation
      tags:
      - Direct Messages
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-dm_conversations-dm_conversation_id-messages
      x-content-type: application/json
      x-accepts: application/json
  /2/dm_conversations/{id}/dm_events:
    get:
      description: Returns DM Events for a DM Conversation
      operationId: DirectMessages_getDmEvents
      security:
      - OAuth2UserToken:
        - dm.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get DM Events for a DM Conversation
      tags:
      - Direct Messages
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-dm_conversations-id-dm_events
      x-accepts: application/json
  /2/dm_events:
    get:
      description: Returns recent DM Events across DM conversations
      operationId: DirectMessages_getRecentDmEvents
      security:
      - OAuth2UserToken:
        - dm.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get recent DM Events
      tags:
      - Direct Messages
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-dm_events
      x-accepts: application/json
  /2/lists:
    post:
      description: Creates a new List.
      operationId: Lists_createNewList
      security:
      - OAuth2UserToken:
        - list.read
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Create List
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-lists
      x-content-type: application/json
      x-accepts: application/json
  /2/lists/{id}:
    delete:
      description: Delete a List that you own.
      operationId: Lists_deleteOwnedList
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Delete List
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-lists-id
      x-accepts: application/json
    get:
      description: Returns a List.
      operationId: Lists_lookupByListId
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: List lookup by List ID.
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-lists-id
      x-accepts: application/json
    put:
      description: Update a List that you own.
      operationId: Lists_updateOwnedList
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Update List.
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--2-lists-id
      x-content-type: application/json
      x-accepts: application/json
  /2/lists/{id}/followers:
    get:
      description: Returns a list of Users that follow a List by the provided List
        ID
      operationId: Users_getFollowersByListId
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that follow a List by the provided List ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-lists-id-followers
      x-accepts: application/json
  /2/lists/{id}/members:
    get:
      description: Returns a list of Users that are members of a List by the provided
        List ID.
      operationId: Users_getMembersByListId
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are members of a List by the provided List
        ID.
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-lists-id-members
      x-accepts: application/json
    post:
      description: Causes a User to become a member of a List.
      operationId: Lists_addMember
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Add a List member
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-lists-id-members
      x-content-type: application/json
      x-accepts: application/json
  /2/lists/{id}/members/{user_id}:
    delete:
      description: Causes a User to be removed from the members of a List.
      operationId: Lists_removeMember
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Remove a List member
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-lists-id-members-user_id
      x-accepts: application/json
  /2/lists/{id}/tweets:
    get:
      description: Returns a list of Tweets associated with the provided List ID.
      operationId: Tweets_listByListId
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: List Tweets timeline by List ID.
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-lists-id-tweets
      x-accepts: application/json
  /2/openapi.json:
    get:
      description: Full OpenAPI Specification in JSON format. (See https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)
      operationId: General_getOpenApiSpec
      summary: Returns the OpenAPI Specification document.
      tags:
      - General
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-openapi.json
      x-accepts: application/json
  /2/spaces:
    get:
      description: Returns a variety of information about the Spaces specified by
        the requested IDs
      operationId: Spaces_lookupSpaceIds
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup up Space IDs
      tags:
      - Spaces
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-spaces
      x-accepts: application/json
  /2/spaces/by/creator_ids:
    get:
      description: Returns a variety of information about the Spaces created by the
        provided User IDs
      operationId: Spaces_lookupByCreatorIds
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup by their creators
      tags:
      - Spaces
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-spaces-by-creator_ids
      x-accepts: application/json
  /2/spaces/search:
    get:
      description: Returns Spaces that match the provided query.
      operationId: Spaces_findMatchingSpaces
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Search for Spaces
      tags:
      - Spaces
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-spaces-search
      x-accepts: application/json
  /2/spaces/{id}:
    get:
      description: Returns a variety of information about the Space specified by the
        requested ID
      operationId: Spaces_lookupSpaceById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Space lookup by Space ID
      tags:
      - Spaces
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-spaces-id
      x-accepts: application/json
  /2/spaces/{id}/buyers:
    get:
      description: Retrieves the list of Users who purchased a ticket to the given
        space
      operationId: Spaces_getBuyersList
      security:
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Retrieve the list of Users who purchased a ticket to the given space
      tags:
      - Spaces
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-spaces-id-buyers
      x-accepts: application/json
  /2/spaces/{id}/tweets:
    get:
      description: Retrieves Tweets shared in the specified Space.
      operationId: Spaces_getTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - space.read
        - tweet.read
        - users.read
      summary: Retrieve Tweets from a Space.
      tags:
      - Spaces
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-spaces-id-tweets
      x-accepts: application/json
  /2/tweets:
    get:
      description: Returns a variety of information about the Tweet specified by the
        requested ID.
      operationId: Tweets_lookupByTweetIds
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Tweet lookup by Tweet IDs
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets
      x-accepts: application/json
    post:
      description: Causes the User to create a Tweet under the authorized account.
      operationId: Tweets_createTweet
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Creation of a Tweet
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-tweets
      x-content-type: application/json
      x-accepts: application/json
  /2/tweets/compliance/stream:
    get:
      description: Streams 100% of compliance data for Tweets
      operationId: Compliance_streamData
      security:
      - BearerToken: []
      summary: Tweets Compliance stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-compliance-stream
      x-accepts: application/json
  /2/tweets/counts/all:
    get:
      description: Returns Tweet Counts that match a search query.
      operationId: Tweets_getTweetCounts
      security:
      - BearerToken: []
      summary: Full archive search counts
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-counts-all
      x-accepts: application/json
  /2/tweets/counts/recent:
    get:
      description: Returns Tweet Counts from the last 7 days that match a search query.
      operationId: Tweets_getRecentTweetCounts
      security:
      - BearerToken: []
      summary: Recent search counts
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-counts-recent
      x-accepts: application/json
  /2/tweets/firehose/stream:
    get:
      description: Streams 100% of public Tweets.
      operationId: Tweets_getFirehoseStream
      security:
      - BearerToken: []
      summary: Firehose stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-firehose-stream
      x-accepts: application/json
  /2/tweets/label/stream:
    get:
      description: Streams 100% of labeling events applied to Tweets
      operationId: Compliance_streamTweetsLabelEvents
      security:
      - BearerToken: []
      summary: Tweets Label stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-label-stream
      x-accepts: application/json
  /2/tweets/sample/stream:
    get:
      description: Streams a deterministic 1% of public Tweets.
      operationId: Tweets_streamSample
      security:
      - BearerToken: []
      summary: Sample stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-sample-stream
      x-accepts: application/json
  /2/tweets/sample10/stream:
    get:
      description: Streams a deterministic 10% of public Tweets.
      operationId: Tweets_streamSample10
      security:
      - BearerToken: []
      summary: Sample 10% stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-sample10-stream
      x-accepts: application/json
  /2/tweets/search/all:
    get:
      description: Returns Tweets that match a search query.
      operationId: Tweets_searchAll
      security:
      - BearerToken: []
      summary: Full-archive search
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-search-all
      x-accepts: application/json
  /2/tweets/search/recent:
    get:
      description: Returns Tweets from the last 7 days that match a search query.
      operationId: Tweets_getRecentTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Recent search
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-search-recent
      x-accepts: application/json
  /2/tweets/search/stream:
    get:
      description: Streams Tweets matching the stream's active rule set.
      operationId: Tweets_getFilteredStream
      security:
      - BearerToken: []
      summary: Filtered stream
      tags:
      - Tweets
      x-twitter-streaming: true
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-search-stream
      x-accepts: application/json
  /2/tweets/search/stream/rules:
    get:
      description: "Returns rules from a User's active rule set. Users can fetch all\
        \ of their rules or a subset, specified by the provided rule ids."
      operationId: Tweets_searchStreamRules
      security:
      - BearerToken: []
      summary: Rules lookup
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-search-stream-rules
      x-accepts: application/json
    post:
      description: "Add or delete rules from a User's active rule set. Users can provide\
        \ unique, optionally tagged rules to add. Users can delete their entire rule\
        \ set or a subset specified by rule ids or values."
      operationId: Tweets_addOrDeleteRules
      security:
      - BearerToken: []
      summary: Add/Delete rules
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-tweets-search-stream-rules
      x-content-type: application/json
      x-accepts: application/json
  /2/tweets/{id}:
    delete:
      description: Delete specified Tweet (in the path) by ID.
      operationId: Tweets_deleteById
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Tweet delete by Tweet ID
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-tweets-id
      x-accepts: application/json
    get:
      description: Returns a variety of information about the Tweet specified by the
        requested ID.
      operationId: Tweets_lookupById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Tweet lookup by Tweet ID
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-id
      x-accepts: application/json
  /2/tweets/{id}/liking_users:
    get:
      description: Returns a list of Users that have liked the provided Tweet ID
      operationId: Users_listLikingUsers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - like.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that have liked the provided Tweet ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-id-liking_users
      x-accepts: application/json
  /2/tweets/{id}/quote_tweets:
    get:
      description: Returns a variety of information about each Tweet that quotes the
        Tweet specified by the requested ID.
      operationId: Tweets_getQuoteTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Retrieve Tweets that quote a Tweet.
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-id-quote_tweets
      x-accepts: application/json
  /2/tweets/{id}/retweeted_by:
    get:
      description: Returns a list of Users that have retweeted the provided Tweet
        ID
      operationId: Users_getRetweetedByTweetIdUsers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that have retweeted the provided Tweet ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-tweets-id-retweeted_by
      x-accepts: application/json
  /2/tweets/{tweet_id}/hidden:
    put:
      description: Hides or unhides a reply to an owned conversation.
      operationId: Tweets_hideReply
      security:
      - OAuth2UserToken:
        - tweet.moderate.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Hide replies
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--2-tweets-tweet_id-hidden
      x-content-type: application/json
      x-accepts: application/json
  /2/users:
    get:
      description: This endpoint returns information about Users. Specify Users by
        their ID.
      operationId: Users_lookupByIds
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by IDs
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users
      x-accepts: application/json
  /2/users/by:
    get:
      description: This endpoint returns information about Users. Specify Users by
        their username.
      operationId: Users_lookupByUsernames
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by usernames
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-by
      x-accepts: application/json
  /2/users/by/username/{username}:
    get:
      description: This endpoint returns information about a User. Specify User by
        username.
      operationId: Users_lookupByUsername
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by username
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-by-username-username
      x-accepts: application/json
  /2/users/compliance/stream:
    get:
      description: Streams 100% of compliance data for Users
      operationId: Compliance_streamUsersData
      security:
      - BearerToken: []
      summary: Users Compliance stream
      tags:
      - Compliance
      x-twitter-streaming: true
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-compliance-stream
      x-accepts: application/json
  /2/users/me:
    get:
      description: This endpoint returns information about the requesting User.
      operationId: Users_lookupMe
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup me
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-me
      x-accepts: application/json
  /2/users/{id}:
    get:
      description: This endpoint returns information about a User. Specify User by
        ID.
      operationId: Users_lookupById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User lookup by ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id
      x-accepts: application/json
  /2/users/{id}/blocking:
    get:
      description: Returns a list of Users that are blocked by the provided User ID
      operationId: Users_getBlockedUsers
      security:
      - OAuth2UserToken:
        - block.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are blocked by provided User ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-blocking
      x-accepts: application/json
    post:
      description: Causes the User (in the path) to block the target User. The User
        (in the path) must match the User context authorizing the request
      operationId: Users_blockUserById
      security:
      - OAuth2UserToken:
        - block.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Block User by User ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-users-id-blocking
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/bookmarks:
    get:
      description: Returns Tweet objects that have been bookmarked by the requesting
        User
      operationId: Bookmarks_getUserBookmarks
      security:
      - OAuth2UserToken:
        - bookmark.read
        - tweet.read
        - users.read
      summary: Bookmarks by User
      tags:
      - Bookmarks
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-bookmarks
      x-accepts: application/json
    post:
      description: Adds a Tweet (ID in the body) to the requesting User's (in the
        path) bookmarks
      operationId: Bookmarks_addTweet
      security:
      - OAuth2UserToken:
        - bookmark.write
        - tweet.read
        - users.read
      summary: Add Tweet to Bookmarks
      tags:
      - Bookmarks
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-users-id-bookmarks
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/bookmarks/{tweet_id}:
    delete:
      description: Removes a Tweet from the requesting User's bookmarked Tweets.
      operationId: Bookmarks_removeTweet
      security:
      - OAuth2UserToken:
        - bookmark.write
        - tweet.read
        - users.read
      summary: Remove a bookmarked Tweet
      tags:
      - Bookmarks
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-users-id-bookmarks-tweet_id
      x-accepts: application/json
  /2/users/{id}/followed_lists:
    get:
      description: Returns a User's followed Lists.
      operationId: Lists_getFollowed
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get User's Followed Lists
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-followed_lists
      x-accepts: application/json
    post:
      description: Causes a User to follow a List.
      operationId: Lists_followList
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Follow a List
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-users-id-followed_lists
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/followed_lists/{list_id}:
    delete:
      description: Causes a User to unfollow a List.
      operationId: Lists_unfollowList
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unfollow a List
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-users-id-followed_lists-list_id
      x-accepts: application/json
  /2/users/{id}/followers:
    get:
      description: Returns a list of Users who are followers of the specified User
        ID.
      operationId: Users_getFollowersById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - follows.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Followers by User ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-followers
      x-accepts: application/json
  /2/users/{id}/following:
    get:
      description: Returns a list of Users that are being followed by the provided
        User ID
      operationId: Users_getFollowingUsers
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - follows.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Following by User ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-following
      x-accepts: application/json
    post:
      description: "Causes the User(in the path) to follow, or “request to follow”\
        \ for protected Users, the target User. The User(in the path) must match the\
        \ User context authorizing the request"
      operationId: Users_followUser
      security:
      - OAuth2UserToken:
        - follows.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Follow User
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-users-id-following
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/liked_tweets:
    get:
      description: Returns a list of Tweets liked by the provided User ID
      operationId: Tweets_getLikedTweets
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - like.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns Tweet objects liked by the provided User ID
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-liked_tweets
      x-accepts: application/json
  /2/users/{id}/likes:
    post:
      description: Causes the User (in the path) to like the specified Tweet. The
        User in the path must match the User context authorizing the request.
      operationId: Tweets_likeTweet
      security:
      - OAuth2UserToken:
        - like.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to like the specified Tweet
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-users-id-likes
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/likes/{tweet_id}:
    delete:
      description: Causes the User (in the path) to unlike the specified Tweet. The
        User must match the User context authorizing the request
      operationId: Tweets_unlikeTweetById
      security:
      - OAuth2UserToken:
        - like.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to unlike the specified Tweet
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-users-id-likes-tweet_id
      x-accepts: application/json
  /2/users/{id}/list_memberships:
    get:
      description: Get a User's List Memberships.
      operationId: Lists_getUserMemberships
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's List Memberships
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-list_memberships
      x-accepts: application/json
  /2/users/{id}/mentions:
    get:
      description: Returns Tweet objects that mention username associated to the provided
        User ID
      operationId: Tweets_getMentionsById
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User mention timeline by User ID
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-mentions
      x-accepts: application/json
  /2/users/{id}/muting:
    get:
      description: Returns a list of Users that are muted by the provided User ID
      operationId: Users_getMutedUsersById
      security:
      - OAuth2UserToken:
        - mute.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Returns User objects that are muted by the provided User ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-muting
      x-accepts: application/json
    post:
      description: Causes the User (in the path) to mute the target User. The User
        (in the path) must match the User context authorizing the request.
      operationId: Users_muteUserById
      security:
      - OAuth2UserToken:
        - mute.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Mute User by User ID.
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-users-id-muting
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/owned_lists:
    get:
      description: Get a User's Owned Lists.
      operationId: Lists_getUserOwnedLists
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's Owned Lists.
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-owned_lists
      x-accepts: application/json
  /2/users/{id}/pinned_lists:
    get:
      description: Get a User's Pinned Lists.
      operationId: Lists_getUserPinnedLists
      security:
      - OAuth2UserToken:
        - list.read
        - tweet.read
        - users.read
      - UserToken: []
      summary: Get a User's Pinned Lists
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-pinned_lists
      x-accepts: application/json
    post:
      description: Causes a User to pin a List.
      operationId: Lists_pinList
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Pin a List
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-users-id-pinned_lists
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/pinned_lists/{list_id}:
    delete:
      description: Causes a User to remove a pinned List.
      operationId: Lists_unpinList
      security:
      - OAuth2UserToken:
        - list.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unpin a List
      tags:
      - Lists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-users-id-pinned_lists-list_id
      x-accepts: application/json
  /2/users/{id}/retweets:
    post:
      description: Causes the User (in the path) to retweet the specified Tweet. The
        User in the path must match the User context authorizing the request.
      operationId: Tweets_retweetTweetById
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to retweet the specified Tweet.
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--2-users-id-retweets
      x-content-type: application/json
      x-accepts: application/json
  /2/users/{id}/retweets/{source_tweet_id}:
    delete:
      description: Causes the User (in the path) to unretweet the specified Tweet.
        The User must match the User context authorizing the request
      operationId: Tweets_unretweetById
      security:
      - OAuth2UserToken:
        - tweet.read
        - tweet.write
        - users.read
      - UserToken: []
      summary: Causes the User (in the path) to unretweet the specified Tweet
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-users-id-retweets-source_tweet_id
      x-accepts: application/json
  /2/users/{id}/timelines/reverse_chronological:
    get:
      description: Returns Tweet objects that appears in the provided User ID's home
        timeline
      operationId: Tweets_getUserHomeTimeline
      security:
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User home timeline by User ID
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-timelines-reverse_chronological
      x-accepts: application/json
  /2/users/{id}/tweets:
    get:
      description: Returns a list of Tweets authored by the provided User ID
      operationId: Tweets_listByUserId
      security:
      - BearerToken: []
      - OAuth2UserToken:
        - tweet.read
        - users.read
      - UserToken: []
      summary: User Tweets timeline by User ID
      tags:
      - Tweets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--2-users-id-tweets
      x-accepts: application/json
  /2/users/{source_user_id}/blocking/{target_user_id}:
    delete:
      description: Causes the source User to unblock the target User. The source User
        must match the User context authorizing the request
      operationId: Users_unblockUserById
      security:
      - OAuth2UserToken:
        - block.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unblock User by User ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-users-source_user_id-blocking-target_user_id
      x-accepts: application/json
  /2/users/{source_user_id}/following/{target_user_id}:
    delete:
      description: Causes the source User to unfollow the target User. The source
        User must match the User context authorizing the request
      operationId: Users_unfollowUser
      security:
      - OAuth2UserToken:
        - follows.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unfollow User
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-users-source_user_id-following-target_user_id
      x-accepts: application/json
  /2/users/{source_user_id}/muting/{target_user_id}:
    delete:
      description: Causes the source User to unmute the target User. The source User
        must match the User context authorizing the request
      operationId: Users_unmuteByUserId
      security:
      - OAuth2UserToken:
        - mute.write
        - tweet.read
        - users.read
      - UserToken: []
      summary: Unmute User by User ID
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--2-users-source_user_id-muting-target_user_id
      x-accepts: application/json
components:
  securitySchemes:
    BearerToken:
      scheme: bearer
      type: http
      x-konfig-globally-required-security: false
    OAuth2UserToken:
      flows:
        authorizationCode:
          authorizationUrl: https://api.twitter.com/2/oauth2/authorize
          scopes:
            block.read: Accounts you’ve blocked.
            block.write: Block and unblock accounts for you.
            bookmark.read: Allows an app to read bookmarked Tweets
            bookmark.write: Allows an app to create and delete bookmarks
            dm.read: All your Direct Messages
            dm.write: Send and manage Direct Messages for you
            follows.read: People who follow you and people who you follow.
            follows.write: Follow and unfollow people for you.
            like.read: Tweets you’ve liked and likes you can view.
            like.write: Like and un-like Tweets for you.
            list.read: "Lists, list members, and list followers of lists you’ve created\
              \ or are a member of, including private lists."
            list.write: Create and manage Lists for you.
            mute.read: Accounts you’ve muted.
            mute.write: Mute and unmute accounts for you.
            offline.access: App can request refresh token.
            space.read: Access all of the Spaces you can see.
            tweet.moderate.write: Hide and unhide replies to your Tweets.
            tweet.read: "All the Tweets you can see, including Tweets from protected\
              \ accounts."
            tweet.write: Tweet and retweet for you.
            users.read: "Any account you can see, including protected accounts. Any\
              \ account you can see, including protected accounts."
          tokenUrl: https://api.twitter.com/2/oauth2/token
      type: oauth2
      x-konfig-globally-required-security: false
    UserToken:
      scheme: OAuth
      type: http
      x-konfig-globally-required-security: false

